name: flutter_multi_language_dynamic_app
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  easy_localization: ^3.0.7+1
  flutter_screenutil: ^5.9.3
  shared_preferences: ^2.5.2
  dio: ^5.8.0+1
  flutter_bloc: ^9.1.0
  logger: ^2.5.0
  awesome_dialog: ^3.2.1
  dartz: ^0.10.1
  permission_handler: ^11.4.0
  get_it: ^8.0.3
  skeletonizer: ^1.4.3
  internet_connection_checker: ^3.0.1
  google_maps_flutter: ^2.10.1
  geolocator: ^13.0.2
  go_router: ^14.8.1
  json_serializable: ^6.8.0
  flutter_secure_storage: ^9.2.4

  cupertino_icons: ^1.0.8

dev_dependencies:
  build_runner: ^2.4.8
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
